//
//  Order.swift
//  
//
//  Created by Sten Soosaar on 30.04.2025.
//

import Foundation


public struct Order: Sendable, Identifiable{
	
	public var id:Int?{
		return orderId
	}
	
	/// The account name the trade will be allocated to.
	public var accountName: String?
	
	/// Order side values
	public enum Action: String, Codable, Sendable {
		
		/// Opening long position or closing short position
		case buy = "BUY"
		
		/// Closing long position or opening short position
		case sell = "SELL"
		
		/// For institutional account configured with Long/Short account segments or clearing with a separate account
		case short = "SSHORT"
		
		/// For specially-configured institutional accounts to indicate that long position not yet delivered is being sold
		case long = "SSLONG"
		
	}
	
	/// Order side
	public var action: Action? = nil
	
	///	The API client id which placed the order.
	public var clientId: Int? = 0
	
	public var auxPrice: Double? = nil

	/// Defines the start time of GTC orders.
	public var activeStartTime: Date? = nil
	
	/// Defines the stop time of GTC orders.
	public var activeStopTime: Date? = nil
	
	/// Adjusted Stop orders: specifies where the trailing unit is an amount (set to 0) or a percentage (set to 1)
	public var adjustableTrailingUnit: Int? = nil
	
	/// Adjusted Stop orders: the parent order will be adjusted to the given type when the adjusted trigger price is penetrated.
	public var adjustedOrderType: OrderType? = nil
	
	///Adjusted Stop orders: specifies the stop limit price of the adjusted (STPL LMT) parent.
	public var adjustedStopLimitPrice: Double? = nil
	
	///Adjusted Stop orders: specifies the stop price of the adjusted (STP) parent.
	public var adjustedStopPrice: Double? = nil
	
	///Adjusted Stop orders: specifies the trailing amount of the adjusted (TRAIL) parent.
	public var adjustedTrailingAmount: Double? = nil
	
	///Accepts a string with parameters obtained from advancedOrderRejectJson.
	public var advancedErrorOverride: String? = nil
	
	///Identifies orders generated by algorithmic trading.
	public var algoId: String? = nil
	
	///The list of parameters for the IB algorithm. For more information about IB’s API algorithms
	public var algoParams:[String:String]? = nil
	
	public enum AlgoStrategy: String, Codable, Sendable {
		case arrivalPrice = "ArrivalPx"
		case darkIce = "DarkIce"
		case percentageofVolume = "PctVol"
		case timeWeightedAveragePrice = "Twap"
		case volumeWeightedAveragePrice = "Vwap"
	}
	
	///The algorithm strategy. For more information about IB’s API algorithms
	public var algoStrategy: AlgoStrategy? = nil
	
	///Indicates whether or not all the order has to be filled on a single execution.
	public var allOrNone: Bool? = false
	
	public enum AuctionStrategy: Int, Codable, Sendable {
		case match = 1
		case improvement = 2
		case transparent = 3
	}
	
	/// For BOX orders only.
	public var auctionStrategy: AuctionStrategy? = nil
	
	///Specifies the date to auto cancel the order.
	public var autoCancelDate: Date? = nil
	
	///Cancels the parent order if child order was cancelled.
	public var autoCancelParent: Bool = false
	
	/// Specifies Basis Points for EFP order. The values increment in 0.01% = 1 basis point. For EFP orders only.
	public var basisPoints: Double? = nil
	
	/// Specifies the increment of the Basis Points. For EFP orders only.
	public var basisPointsType: Int? = nil
	
	///If set to true
	public var blockOrder: Bool? = false
	
	///The native cash quantity.
	public var cashQty: Double? = nil
	
	///Specifies the true beneficiary of the order. For IBExecution customers. This value is required for FUT/FOP orders for reporting to the exchange.
	public var clearingAccount: String? = nil

	public enum ClearingIntent: String, Codable, Sendable {
		case ib = "IB"
		case away = "Away"
		case postTradeAllocation = "PTA"
	}
	
	/// For exeuction-only clients to know where do they want their shares to be cleared at.
	public var clearingIntent: ClearingIntent? = nil

	///Dpecifies the offset Off The Midpoint that will be applied to the order. For IBKRATS orders.
	public var competeAgainstBestOffset: Double? = nil
	
	///Conditions determining when the order will be activated or canceled.
	public var conditions: OrderConditions? = nil
	
	///Conditions can determine if an order should become active or canceled.
	public var conditionsCancelOrder: Bool? = false
	
	///Indicates whether or not conditions will also be valid outside Regular Trading Hours.
	public var conditionsIgnoreRth: Bool? = false
	
	///Specifies whether TWS will automatically update the limit price of the order as the underlying price moves. VOL orders only.
	public var continuousUpdate: Bool? = false
	
	///The stock’s Delta. For orders on BOX only.
	public var delta: Double? = nil
	
	///Use this field to enter a value if the value in the deltaNeutralOrderType field is an order type that requires an Aux price
	public var deltaNeutralAuxPrice: Double? = nil
	
	///Specifies the beneficiary of the Delta Neutral order.
	public var deltaNeutralClearingAccount: String? = nil
	
	///Specifies where the clients want their shares to be cleared at. Must be specified by execution-only clients. Valid values are: IB
	public var deltaNeutralClearingIntent: String? = nil
	
	///The unique contract identifier specifying the security in Delta Neutral order.
	public var deltaNeutralConId: Int? = nil
	
	///Identifies third party order origin. Used only when deltaNeutralShortSaleSlot = 2.
	public var deltaNeutralDesignatedLocation: String? = nil
	
	///Specifies whether the order is an Open or a Close order and is used when the hedge involves a CFD and and the order is clearing away.
	public var deltaNeutralOpenClose: String? = nil
	
	///Enter an order type to instruct TWS to submit a delta neutral trade on full or partial execution of the VOL order. VOL orders only. For no hedge delta order to be sent
	public var deltaNeutralOrderType: OrderType? = nil
	
	///Indicates the firm which will settle the Delta Neutral trade. Institutions only.
	public var deltaNeutralSettlingFirm: String? = nil
	
	///Used when the hedge involves a stock and indicates whether or not it is sold short.
	public var deltaNeutralShortSale: Bool? = false
	
	///Indicates a short sale Delta Neutral order. Has a value of 1 (the clearing broker holds shares) or 2 (delivered from a third party). If you use 2
	public var deltaNeutralShortSaleSlot: Int? = nil
	
	///For institutions only. Indicates the location where the shares to short come from. Used only when short sale slot is set to 2 (which means that the shares to short are held elsewhere and not with IB).
	public var designatedLocation: String? = nil
	
	///The amount off the limit price allowed for discretionary orders.
	public var discretionaryAmt: Double? = nil
	
	///Set to true to convert order of type ‘Primary Peg’ to ‘D-Peg’.
	public var discretionaryUpToLimitPrice: Bool? = false
	
	///	The publicly disclosed order size
	public var displaySize: Int? = 0
	
	///Don’t use auto price for hedge.
	public var dontUseAutoPriceForHedge: Bool? = false
	
	///Specifies the duration of the order. Format: yyyymmdd hh:mm:ss TZ. For GTD orders.
	public var duration: Int? = nil
	
	///	Only available with IB Execution-Only accounts with applicable securities. Mark order as exempt from short sale uptick rule.
	public var exemptCode: Int = -1
	
	///Following CME Rule 576, the ExtOperator field will signify if the unique API operator at the time of trading for order management.
	public var extOperator:	String? = nil
	
	///The Financial Advisor group the trade will be allocated to. Use an empty string if not applicable.
	public var faGroup: String? = nil
	
	///The Financial Advisor allocation method the trade will be allocated to. Use an empty string if not applicable.
	public var faMethod: String? = nil
	
	///The Financial Advisor percentage concerning the trade’s allocation. Use an empty string if not applicable.
	public var faPercentage: String? = nil
	
	///Specifies the initial order quantity to be filled.
	public var filledQuantity: Double? = nil
	
	/// Specifies the date and time after which the order will be active. Format: yyyymmdd hh:mm:ss {optional Timezone}.
	public var goodAfterTime: Date? = nil
	
	///The date and time until the order will be active. You must enter GTD as the time in force to use this string. The trade’s “Good Till Date
	public var goodTillDate: Date? = nil
	
	///For hedge orders. Beta = x for Beta hedge orders
	public var hedgeParam: String? = nil
	
	/// Specifies the type of hedge used for hedge orders.
	public enum HedgeType: String, Codable, Sendable {
		
		/// Delta hedge — typically used to maintain a neutral delta position.
		case delta = "D"
		
		/// Beta hedge — used to hedge against beta exposure in a portfolio.
		case beta = "B"
		
		/// FX hedge — used to hedge foreign exchange risk.
		case fx = "F"
		
		/// Pair hedge — used in pair trading strategies.
		case pair = "P"
	}
	
	///For hedge orders.
	public var hedgeType: HedgeType? = nil
	
	///If set to true, the order will not be visible when viewing the market depth. This option only applies to orders routed to the NASDAQ exchange.
	public var hidden: Bool? = true
	
	///Used to specify “imbalance only open orders” or “imbalance only closing orders”.
	public var imbalanceOnly: Bool = false
	
	///	Set to true to create tickets from API orders when TWS is used as an OMS.
	public var isOmsContainer: Bool? = false
	
	///Pegged-to-benchmark orders: indicates whether the order’s pegged price should increase or decreases.
	public var isPeggedChangeAmountDecrease: Bool? = false
	
	///The LIMIT price. Used for limit
	public var lmtPrice: Double? = nil
	
	///Adjusted Stop orders: specifies the price offset for the stop to move in increments.
	public var lmtPriceOffset: Double? = nil
	
	///Following CME Rule 576, the ManualOrderIndicator field will signify if an order is manual (1) or automated (0).
	public var manualOrderIndicator: Int? = nil
	
	///Used by brokers and advisors when manually entering an order request. Format should be “YYYYMMDD-HH:mm:ss” using UTC as the timezone value.
	public var manualOrderTime: String? = nil
	
	///This offset is applied when the spread is an odd number of cents wide. This offset must be in half-penny increments. For IBKRATS orders.
	public var midOffsetAtHalf: Double? = nil
	
	///This offset is applied when the spread is an even number of cents wide. This offset must be in whole-penny increments or zero. For IBKRATS orders.
	public var midOffsetAtWhole: Double? = nil
	
	//MARK: - MIFID
	
	///Identifies the algorithm responsible for investment decisions within the firm. Orders covered under MiFID 2 must include either Mifid2DecisionMaker or Mifid2DecisionAlgo
	public var mifid2DecisionAlgo: String? = nil
	
	///Identifies a person as the responsible party for investment decisions within the firm. Orders covered by MiFID 2 (Markets in Financial Instruments Directive 2) must include either Mifid2DecisionMaker or Mifid2DecisionAlgo field (but not both). Requires TWS 969+.
	public var mifid2DecisionMaker: String? = nil
	
	///For MiFID 2 reporting; identifies the algorithm responsible for the execution of a transaction within the firm. Requires TWS 969+.
	public var mifid2ExecutionAlgo: String? = nil
	
	/// For MiFID 2 reporting; identifies a person as the responsible party for the execution of a transaction within the firm. Requires TWS 969+.
	public var mifid2ExecutionTrader: String? = nil
	

	///Defines the minimum size to compete. For IBKRATS orders.
	public var minCompeteSize: Int? = nil
	
	///Identifies a minimum quantity order type.
	public var minQty: Int? = nil
	
	///	Defines the minimum trade quantity to fill. For IBKRATS orders.
	public var minTradeQty: Int? = nil
	
	
	///Is used to place an order to a model. For example
	public var modelCode: String? = nil
	
	///Orders routed to IBDARK are tagged as “post only” and are held in IB’s order book
	public var notHeld: Bool? = false
	
	//MARK: - ONE CANCELS ALL
	
	///One-Cancels-All group identifier.
	public var ocaGroup: String? = nil
	
	/// Specifies how to handle remaining orders in an OCA (One Cancels All) group when one order is executed.
	///
	/// "With block" options provide overfill protection by ensuring only one order is routed at a time.
	public enum OcaType: Int, Codable, Sendable {
		
		/// Cancel all remaining orders in the group when one order (or part of it) is executed. (With block)
		case cancelAll = 1
		
		case cancelWithBlocking = 2

		/// Reduce the size of remaining orders proportionally. Only one order is routed at a time. (With block)
		case reduceWithBlock = 3

		/// Reduce the size of remaining orders proportionally. All orders may be active simultaneously. (No block)
		case reduceWithoutBlock = 4
	}
	
	/// Tells how to handle remaining orders in an OCA group when one order or part of an order executes
	public var ocaType: OcaType? = nil
	
	public enum OpenClose: String, Codable, Sendable {
		
		/// Open a new position.
		case open = "O"
		
		/// Close an existing position.
		case close = "C"
	}
	
	/**
	 Indicates whether an institutional order is to open or close a position.
		**Usage:**
		- `Action = "BUY"` and `OpenClose = .open` → opens a new position.
		- `Action = "BUY"` and `OpenClose = .close` → closes an existing short position.
	 */
	public var openClose: OpenClose? = nil
	
	///Use to opt out of default SmartRouting for orders routed directly to ASX. This attribute defaults to false unless explicitly set to true. When set to false
	public var optOutSmartRouting: Bool? = false
	
	public struct ComboLeg: Codable, Sendable {
		public var price: Double
	}
	
	///List of Per-leg price following the same sequence combo legs are added. The combo price must be left unspecified when using per-leg prices.
	public var orderComboLegs:[Order.ComboLeg]? = nil
	
	///For internal use only. Use the default value XYZ.
	internal var orderMiscOptions: [String:String]? = nil
	
	internal var referenceExchangeId: String? = nil
	
	///The API client’s order id.
	public var orderId: Int? = nil
	
	///The order reference. Intended for institutional customers only
	public var orderRef: String? = nil
	
	///The order’s type.
	public var orderType: OrderType? = nil
	
	public enum Origin: Int, Codable, Sendable {
		case customer 			= 0
		case firm 				= 1
		case unknown 			= 2
	}
	
	/// Identifies the type of customer from which the order originated. Valid values are 0 (customer), 1 (firm).
	public var origin: Origin = .customer

	///If set to true, allows orders to also trigger or fill outside of regular trading hours.
	public var outsideRth: Bool = true
	
	///Overrides TWS constraints. Precautionary constraints are defined on the TWS Presets page
	public var overridePercentageConstraints: Bool? = false
	
	///The order ID of the parent order, used for bracket and auto trailing stop orders.
	public var parentId: Int? = 0
	
	///Parent order Id.
	public var parentPermId: Double? = nil
	
	///Pegged-to-benchmark orders: amount by which the order’s pegged price should move.
	public var peggedChangeAmount: Double? = nil
	
	///The percent offset amount for relative orders.
	public var percentOffset: Double? = nil
	
	///The Host order identifier.
	public var permId: Int? = 0
	
	///	Value must be positive
	public var postToAts: Int? = nil
	
	///Randomizes the order’s price. Only for Volatility and Pegged to Volatility orders.
	public var randomizePrice: Bool? = false
	
	///Randomizes the order’s size. Only for Volatility and Pegged to Volatility orders.
	public var randomizeSize: Bool? = false
	
	///Identifies the reference future conId.
	public var refFuturesConId: Int? = nil
	
	///Pegged-to-benchmark orders: the amount the reference contract needs to move to adjust the pegged order.
	public var referenceChangeAmount: Double? = nil

	///	Pegged-to-benchmark orders: this attribute will contain the conId of the contract against which the order will be pegged.
	public var referenceContractId: Int? = nil
	
	///Pegged-to-benchmark orders: the exchange against which we want to observe the reference contract.
	public var referenceExchange: String? = nil
	
	/// Specifies how the reference price is calculated for VOL orders (used for options and stock range price monitoring).
	public enum ReferencePriceType: Int, Codable, Sendable {
		
		/// Uses the average of the National Best Bid and Offer (NBBO) as the reference price.
		case averageNBBO = 1
		
		/// Uses either the National Best Bid (NBB) or National Best Offer (NBO) depending on the order action and option right.
		case bidOrAsk = 2
	}

	public var referencePriceType: ReferencePriceType? = nil
	
	///Routes market order to Best Bid Offer.
	public var routeMarketableToBbo: Bool = false
	
	/// Represents Rule 80A trade classification codes.
	/// These codes indicate whether the order is for an individual, an agency, or another member,
	/// and whether it is submitted under proprietary or PTIA conditions.
	public enum Rule80AType: String, Codable, Sendable {
		
		/// Individual investor order.
		case individual = "I"
		
		/// Agency order.
		case agency = "A"
		
		/// Agent other member order.
		case agentOtherMember = "W"
		
		/// Individual PTIA (Proprietary Trading Information Aggregator) order.
		case individualPTIA = "J"
		
		/// Agency PTIA order.
		case agencyPTIA = "U"
		
		/// Agent other member PTIA order.
		case agentOtherMemberPTIA = "M"
		
		/// Individual PT (Proprietary Trading) order.
		case individualPT = "K"
		
		/// Agency PT order.
		case agencyPT = "Y"
		
		/// Agent other member PT order.
		case agentOtherMemberPT = "N"
	}
	
	public var rule80A: Rule80AType? = nil
	
	///Restarts the Scale series if the order is cancelled. For extended scale orders.
	public var scaleAutoReset: Bool? = false
	
	///Specifies the initial quantity to be filled. For extended scale orders.
	public var scaleInitFillQty: Int? = nil
	
	///	Defines the size of the first
	public var scaleInitLevelSize: Int? = nil
	
	/// The initial position of the Scale order. For extended scale orders.
	public var scaleInitPosition: Int? = nil
	
	/// Specifies the interval when the price is adjusted. For extended Scale orders.
	public var scalePriceAdjustInterval: Int? = nil
	
	/// Modifies the value of the Scale order. For extended Scale orders.
	public var scalePriceAdjustValue: Double? = nil
	
	/// Defines the price increment between scale components. For Scale orders only. This value is compulsory.
	public var scalePriceIncrement: Double? = nil
	
	/// Specifies the offset when to adjust profit. For extended scale orders.
	public var scaleProfitOffset: Double? = nil
	
	/// Defines the random percent by which to adjust the position. For extended scale orders.
	public var scaleRandomPercent: Bool? = false
	
	/// Defines the order size of the subsequent scale order components. For Scale orders only. Used in conjunction with scaleInitLevelSize().
	public var scaleSubsLevelSize: Int? = nil
	
	///	The list of scale orders. Used for scale orders.
	public var scaleTable: String? = nil
	
	/// Indicates the firm which will settle the trade. Institutions only.
	public var settlingFirm: String? = nil
	
	/// Identifies the Shareholder.
	public var shareholder: String? = nil
	
	public enum ShortSaleSlot: Int, Codable, Sendable{
		case broker = 1
		case thirdParty = 2
	}

	public var shortSaleSlot: ShortSaleSlot? = nil
	
	/// Advanced parameters for Smart combo routing. These features are for both guaranteed and nonguaranteed combination orders routed to Smart
	public var smartComboRoutingParams: [String:String]? = nil
	
	/**
	 The Solicited field should be used for orders initiated or recommended by the broker or adviser that were approved by the client (by phone, email, chat, verbally, etc.) prior to entry.
	 Please note that orders that the adviser or broker placed without specifically discussing with the client are discretionary orders, not solicited.
	 */
	public var solicited: Bool? = false
	
	///The auction’s starting price. For BOX orders only.
	public var startingPrice: Double? = nil
	
	///The lower value for the acceptable underlying stock price range. For price improvement option orders on BOX and VOL orders with dynamic management.
	public var stockRangeLower: Double? = nil
	
	///	The upper value for the acceptable underlying stock price range. For price improvement option orders on BOX and VOL orders with dynamic management.
	public var stockRangeUpper: Double? = nil
	
	///The stock’s reference price. The reference price is used for VOL orders to compute the limit price sent to an exchange (whether or not Continuous Update is selected)
	public var stockRefPrice: Double? = nil
	
	///If set to true
	public var sweepToFill: Bool? = false
	
	///Define the Soft Dollar Tier used for the order. Only provided for registered professional advisors and hedge and mutual funds.
	public var softDollarTiers: SoftDollarTier? = nil
	
	/// Represents the time in force for an order, specifying how long the order will remain active.
	public enum TimeInForce: String, Codable, Sendable {
		
		/// Valid for the day only. The order expires at the end of the trading day if not filled.
		case day = "DAY"
		
		/**
		 Good Until Canceled.
		 The order remains active until executed or manually canceled.
		 Automatically canceled under these conditions:
		 - Stock split, exchange, or distribution.
		 - No IB account login for 90 days.
		 - End of the calendar quarter following the current quarter.
		 Note: Modified orders get a new auto-expire date.
		 GTC orders are not adjusted for dividends.
		 */
		case gtc = "GTC"
		
		/// Immediate or Cancel. Any portion not immediately filled is canceled.
		case ioc = "IOC"
		
		/**
		 Good Until Date.
		 Remains active until executed or until the close of market on the specified date.
		 */
		case gtd = "GTD"
		
		/// Market-on-open (MOO) or limit-on-open (LOO) order.
		case opg = "OPG"
		
		/// Fill or Kill. Entire order must be filled immediately or the whole order is canceled.
		case fok = "FOK"
		
		/// Day Until Canceled. Similar to DAY but may be used with specific brokers or platforms.
		case dtc = "DTC"
		
		/// Undocumented
		case gtt = "GTT"
		
		/// Undocumented
		case auc = "AUC"
		
		/// Undocumented
		case gtx = "GTX"

	}
	
	///Time in force
	public var tif: TimeInForce? = nil
	
	///The number of positions being bought/sold.
	public var totalQuantity: Double? = nil
	
	///Trail stop price for TRAIL LIMIT orders.
	public var trailStopPrice: Double? = nil
	
	///Specifies the trailing amount of a trailing stop order as a percentage. Observe the following guidelines when using the trailingPercent field:
	public var trailingPercent: Double? = nil
	
	///Specifies whether the order will be transmitted by TWS. If set to false, the order will be created at TWS but will not be sent.
	public var transmit: Bool = true
	
	/// Specifies how Simulated Stop, Stop-Limit, and Trailing Stop orders are triggered.
	public enum TriggerMethod: Int, Codable, Sendable {
		
		/**
		 Default behavior:
		 - For OTC stocks and US options: uses the "double bid/ask" method.
		 - For all other instruments: uses the "last" price method.
		 */
		case `default` = 0
		
		/// trigger based on two consecutive bid or ask prices.
		case doubleBidAsk = 1
		
		/// trigger based on the last traded price.
		case last = 2
		
		/// Utriggers on two consecutive last prices.
		case doubleLast = 3
		
		///  triggers on a single bid or ask.
		case bidAsk = 4
		
		/// triggers on either the last price or a bid/ask update.
		case lastOrBidAsk = 7
		
		/// triggers based on the mid-point between bid and ask.
		case midPoint = 8
		
	}
	
	///Specifies how Simulated Stop
	public var triggerMethod: TriggerMethod = .default
	
	///Adjusted Stop orders: specifies the trigger price to execute.
	public var triggerPrice: Double? = nil
	
	/// Specifies wether to use Price Management Algo. CTCI users only.
	public var usePriceMgmtAlgo: Bool = false
	
	///The option price in volatility
	public var volatility: Double? = nil
	
	/// Specifies the type of volatility used in a volatility-based order.
	public enum VolatilityType: Int, Codable, Sendable {
		
		/// Daily volatility — typically used for short-term pricing models.
		case daily = 1
		
		/// Annual volatility — used for long-term or standardized volatility inputs.
		case annual = 2
	}

	public var volatilityType: VolatilityType? = nil
	
	///Allows to retrieve the commissions and margin information. When placing an order with this attribute set to true
	public var whatIf: Bool = false
	
	/**
	 Required for Nondisclosed Omnibus Accounts. A unique identifier for each account within the Omnibus structure to signify the account holder being traded.
	 Best practice (Not Required): clients should look to hash this value, using something along the lines of 5 digits of SHA1 of the account number.
	 This should not be implemented for non-omnibus accounts.
	*/
	public var customerAccount:	String? = nil
	
	/// Required for Nondisclosed Omnibus Accounts Signify whether or not the subaccount is classified as Professional or Non-Professional.
	/// This should not be implemented for non-omnibus accounts.
	public var professionalCustomer: Bool? = false
	
	public var bondAccruedInterest: Double? = nil
	
	public var includeOvernight: Bool = false
	
	public init() {}
	
}

